### ISSUE TITLE
[Atividade 04] Entendimento de negócio

### ISSUE THREAD

**Issue by pinheirolucasdev** [Lucas-p00/avanti-bootcamp-cdd#1]
Compreender completamente, de uma perspectiva de negócios, o que realmente deve ser feito no projeto, em seguida:

 - [x] Modificar o arquivo README.md, contendo um resumo do projeto que será construído. Tente apresentar uma justificativa para o projeto.
 - [x] Inserir um graphical abstract.

**Comment by Lucas-p00** [comment]
## Atividade 04 - Entendimento de negócio

#### Resumo do projeto
Este projeto tem como objetivo analisar o conjunto de dados do Titanic, investigando os principais fatores que influenciaram a sobrevivência dos passageiros durante o desastre. 

#### Modificações
O arquivo README.md foi modificado adicionando o título, resumo do projeto e um graphical abstract indicando os passos iniciais.

#### Arquivo
[README.md](https://github.com/Lucas-p00/avanti-bootcamp-cdd/blob/master/README.md)

**Comment by pinheirolucasdev** [comment]
## Atividade 04 - Entendimento de negócio

#### Resumo do projeto
Este projeto tem como objetivo analisar o conjunto de dados do Titanic, investigando os principais fatores que influenciaram a sobrevivência dos passageiros durante o desastre. 

#### Modificações
O arquivo README.md foi modificado adicionando o título, resumo do projeto e um graphical abstract indicando os passos iniciais.

#### Arquivo
[README.md](https://github.com/Lucas-p00/avanti-bootcamp-cdd/blob/master/README.md)
